import 'package:flutter/material.dart';

/// Registry of all selectable category icons.
///
/// Keys are the icon identifier strings stored in the database.
/// Used to resolve icon names to [IconData] across the categories feature.
const Map<String, IconData> kCategoryIcons = {
  // ── Food & Drink ──────────────────────────────────────────────────────────
  'restaurant': Icons.restaurant_rounded,
  'coffee': Icons.coffee_rounded,
  'local_bar': Icons.local_bar_rounded,
  'fastfood': Icons.fastfood_rounded,
  'cake': Icons.cake_rounded,
  'local_grocery_store': Icons.local_grocery_store_rounded,
  'lunch_dining': Icons.lunch_dining_rounded,
  'dinner_dining': Icons.dinner_dining_rounded,
  'bakery_dining': Icons.bakery_dining_rounded,
  'ramen_dining': Icons.ramen_dining_rounded,
  'icecream': Icons.icecream_rounded,
  'local_pizza': Icons.local_pizza_rounded,
  'set_meal': Icons.set_meal_rounded,
  'wine_bar': Icons.wine_bar_rounded,
  'emoji_food_beverage': Icons.emoji_food_beverage_rounded,
  'kitchen': Icons.kitchen_rounded,

  // ── Transport ─────────────────────────────────────────────────────────────
  'directions_car': Icons.directions_car_rounded,
  'directions_bus': Icons.directions_bus_rounded,
  'flight': Icons.flight_rounded,
  'train': Icons.train_rounded,
  'two_wheeler': Icons.two_wheeler_rounded,
  'local_taxi': Icons.local_taxi_rounded,
  'directions_boat': Icons.directions_boat_rounded,
  'electric_car': Icons.electric_car_rounded,
  'local_gas_station': Icons.local_gas_station_rounded,
  'local_parking': Icons.local_parking_rounded,
  'directions_bike': Icons.directions_bike_rounded,
  'subway': Icons.subway_rounded,
  'electric_scooter': Icons.electric_scooter_rounded,
  'car_repair': Icons.car_repair_rounded,

  // ── Bills & Finance ───────────────────────────────────────────────────────
  'receipt_long': Icons.receipt_long_rounded,
  'payments': Icons.payments_rounded,
  'account_balance': Icons.account_balance_rounded,
  'credit_card': Icons.credit_card_rounded,
  'savings': Icons.savings_rounded,
  'trending_up': Icons.trending_up_rounded,
  'trending_down': Icons.trending_down_rounded,
  'attach_money': Icons.attach_money_rounded,
  'currency_exchange': Icons.currency_exchange_rounded,
  'price_check': Icons.price_check_rounded,
  'wallet': Icons.account_balance_wallet_rounded,
  'monetization_on': Icons.monetization_on_rounded,
  'request_quote': Icons.request_quote_rounded,
  'paid': Icons.paid_rounded,
  'sell': Icons.sell_rounded,

  // ── Entertainment ─────────────────────────────────────────────────────────
  'movie': Icons.movie_rounded,
  'music_note': Icons.music_note_rounded,
  'sports_esports': Icons.sports_esports_rounded,
  'sports': Icons.sports_rounded,
  'book': Icons.book_rounded,
  'tv': Icons.tv_rounded,
  'theaters': Icons.theaters_rounded,
  'headphones': Icons.headphones_rounded,
  'videogame_asset': Icons.videogame_asset_rounded,
  'casino': Icons.casino_rounded,
  'sports_soccer': Icons.sports_soccer_rounded,
  'sports_basketball': Icons.sports_basketball_rounded,
  'sports_tennis': Icons.sports_tennis_rounded,
  'pool': Icons.pool_rounded,
  'golf_course': Icons.golf_course_rounded,
  'stadium': Icons.stadium_rounded,
  'celebration': Icons.celebration_rounded,
  'festival': Icons.festival_rounded,
  'camera': Icons.camera_alt_rounded,
  'photo_library': Icons.photo_library_rounded,

  // ── Health & Wellness ─────────────────────────────────────────────────────
  'monitor_heart': Icons.monitor_heart_rounded,
  'local_hospital': Icons.local_hospital_rounded,
  'fitness_center': Icons.fitness_center_rounded,
  'spa': Icons.spa_rounded,
  'psychology': Icons.psychology_rounded,
  'medication': Icons.medication_rounded,
  'health_and_safety': Icons.health_and_safety_rounded,
  'self_improvement': Icons.self_improvement_rounded,
  'medical_services': Icons.medical_services_rounded,
  'biotech': Icons.biotech_rounded,
  'vaccines': Icons.vaccines_rounded,
  'sports_gymnastics': Icons.sports_gymnastics_rounded,
  'emoji_emotions': Icons.emoji_emotions_rounded,
  'nightlife': Icons.nightlife_rounded,
  'bedroom_baby': Icons.bedroom_baby_rounded,

  // ── Home ──────────────────────────────────────────────────────────────────
  'home': Icons.home_rounded,
  'chair': Icons.chair_rounded,
  'build': Icons.build_rounded,
  'cleaning_services': Icons.cleaning_services_rounded,
  'lightbulb': Icons.lightbulb_rounded,
  'water_drop': Icons.water_drop_rounded,
  'bed': Icons.bed_rounded,
  'bathtub': Icons.bathtub_rounded,
  'countertops': Icons.countertops_rounded,
  'yard': Icons.yard_rounded,
  'lock': Icons.lock_rounded,
  'wifi': Icons.wifi_rounded,
  'tv_gen': Icons.tv_rounded,
  'security': Icons.security_rounded,
  'plumbing': Icons.plumbing_rounded,
  'roofing': Icons.roofing_rounded,

  // ── Shopping ──────────────────────────────────────────────────────────────
  'shopping_bag': Icons.shopping_bag_rounded,
  'shopping_cart': Icons.shopping_cart_rounded,
  'checkroom': Icons.checkroom_rounded,
  'watch': Icons.watch_rounded,
  'phone_iphone': Icons.phone_iphone_rounded,
  'laptop': Icons.laptop_rounded,
  'store': Icons.store_rounded,
  'local_mall': Icons.local_mall_rounded,
  'redeem': Icons.redeem_rounded,
  'diamond': Icons.diamond_rounded,
  'dry_cleaning': Icons.dry_cleaning_rounded,
  'local_laundry_service': Icons.local_laundry_service_rounded,

  // ── Education & Work ──────────────────────────────────────────────────────
  'school': Icons.school_rounded,
  'work': Icons.work_rounded,
  'business_center': Icons.business_center_rounded,
  'edit': Icons.edit_rounded,
  'science': Icons.science_rounded,
  'menu_book': Icons.menu_book_rounded,
  'computer': Icons.computer_rounded,
  'print': Icons.print_rounded,
  'library_books': Icons.library_books_rounded,
  'calculate': Icons.calculate_rounded,
  'engineering': Icons.engineering_rounded,
  'architecture': Icons.architecture_rounded,

  // ── Travel & Places ───────────────────────────────────────────────────────
  'travel_explore': Icons.travel_explore_rounded,
  'beach_access': Icons.beach_access_rounded,
  'landscape': Icons.landscape_rounded,
  'hotel': Icons.hotel_rounded,
  'map': Icons.map_rounded,
  'place': Icons.place_rounded,
  'luggage': Icons.luggage_rounded,
  'hiking': Icons.hiking_rounded,
  'camping': Icons.cabin_rounded,
  'sailing': Icons.sailing_rounded,
  'surfing': Icons.surfing_rounded,
  'park': Icons.park_rounded,

  // ── Miscellaneous ─────────────────────────────────────────────────────────
  'pets': Icons.pets_rounded,
  'card_giftcard': Icons.card_giftcard_rounded,
  'volunteer_activism': Icons.volunteer_activism_rounded,
  'child_care': Icons.child_care_rounded,
  'category': Icons.category_rounded,
  'favorite': Icons.favorite_rounded,
  'star': Icons.star_rounded,
  'emoji_nature': Icons.emoji_nature_rounded,
  'notifications': Icons.notifications_rounded,
  'cloud': Icons.cloud_rounded,
  'bolt': Icons.bolt_rounded,
  'recycling': Icons.recycling_rounded,
  'local_florist': Icons.local_florist_rounded,
  'wb_sunny': Icons.wb_sunny_rounded,
};

/// Resolves an icon name string to an [IconData].
///
/// Returns [Icons.category_rounded] as fallback for unknown names.
IconData resolveCategoryIcon(String? iconName) {
  if (iconName == null || iconName.isEmpty) return Icons.category_rounded;
  return kCategoryIcons[iconName] ?? Icons.category_rounded;
}

/// Human-readable labels for each icon, keyed by language code.
///
/// Fallback chain: requested language → 'en' → raw key.
const Map<String, Map<String, String>> kCategoryIconTranslations = {
  // Food & Drink
  'restaurant': {'en': 'Restaurant', 'es': 'Restaurante'},
  'coffee': {'en': 'Coffee', 'es': 'Café'},
  'local_bar': {'en': 'Bar', 'es': 'Bar'},
  'fastfood': {'en': 'Fast Food', 'es': 'Comida Rápida'},
  'cake': {'en': 'Cake', 'es': 'Pastel'},
  'local_grocery_store': {'en': 'Grocery Store', 'es': 'Supermercado'},
  'lunch_dining': {'en': 'Lunch', 'es': 'Almuerzo'},
  'dinner_dining': {'en': 'Dinner', 'es': 'Cena'},
  'bakery_dining': {'en': 'Bakery', 'es': 'Panadería'},
  'ramen_dining': {'en': 'Ramen', 'es': 'Ramen'},
  'icecream': {'en': 'Ice Cream', 'es': 'Helado'},
  'local_pizza': {'en': 'Pizza', 'es': 'Pizza'},
  'set_meal': {'en': 'Set Meal', 'es': 'Menú del Día'},
  'wine_bar': {'en': 'Wine', 'es': 'Vino'},
  'emoji_food_beverage': {'en': 'Drinks', 'es': 'Bebidas'},
  'kitchen': {'en': 'Kitchen', 'es': 'Cocina'},
  // Transport
  'directions_car': {'en': 'Car', 'es': 'Coche'},
  'directions_bus': {'en': 'Bus', 'es': 'Autobús'},
  'flight': {'en': 'Flight', 'es': 'Vuelo'},
  'train': {'en': 'Train', 'es': 'Tren'},
  'two_wheeler': {'en': 'Motorcycle', 'es': 'Moto'},
  'local_taxi': {'en': 'Taxi', 'es': 'Taxi'},
  'directions_boat': {'en': 'Boat', 'es': 'Barco'},
  'electric_car': {'en': 'Electric Car', 'es': 'Coche Eléctrico'},
  'local_gas_station': {'en': 'Gas Station', 'es': 'Gasolinera'},
  'local_parking': {'en': 'Parking', 'es': 'Estacionamiento'},
  'directions_bike': {'en': 'Bike', 'es': 'Bicicleta'},
  'subway': {'en': 'Subway / Metro', 'es': 'Metro'},
  'electric_scooter': {'en': 'Scooter', 'es': 'Patinete Eléctrico'},
  'car_repair': {'en': 'Car Repair', 'es': 'Taller'},
  // Bills & Finance
  'receipt_long': {'en': 'Bills', 'es': 'Facturas'},
  'payments': {'en': 'Payments', 'es': 'Pagos'},
  'account_balance': {'en': 'Bank', 'es': 'Banco'},
  'credit_card': {'en': 'Credit Card', 'es': 'Tarjeta de Crédito'},
  'savings': {'en': 'Savings', 'es': 'Ahorros'},
  'trending_up': {'en': 'Income', 'es': 'Ingresos'},
  'trending_down': {'en': 'Expense', 'es': 'Gastos'},
  'attach_money': {'en': 'Money', 'es': 'Dinero'},
  'currency_exchange': {'en': 'Exchange', 'es': 'Cambio'},
  'price_check': {'en': 'Price Check', 'es': 'Precio'},
  'wallet': {'en': 'Wallet', 'es': 'Cartera'},
  'monetization_on': {'en': 'Earnings', 'es': 'Ganancias'},
  'request_quote': {'en': 'Quote', 'es': 'Presupuesto'},
  'paid': {'en': 'Paid', 'es': 'Pagado'},
  'sell': {'en': 'Sale', 'es': 'Venta'},
  // Entertainment
  'movie': {'en': 'Movies', 'es': 'Películas'},
  'music_note': {'en': 'Music', 'es': 'Música'},
  'sports_esports': {'en': 'Video Games', 'es': 'Videojuegos'},
  'sports': {'en': 'Sports', 'es': 'Deportes'},
  'book': {'en': 'Books', 'es': 'Libros'},
  'tv': {'en': 'TV', 'es': 'Televisión'},
  'theaters': {'en': 'Theater', 'es': 'Teatro'},
  'headphones': {'en': 'Headphones', 'es': 'Auriculares'},
  'videogame_asset': {'en': 'Gaming', 'es': 'Gaming'},
  'casino': {'en': 'Casino', 'es': 'Casino'},
  'sports_soccer': {'en': 'Football', 'es': 'Fútbol'},
  'sports_basketball': {'en': 'Basketball', 'es': 'Baloncesto'},
  'sports_tennis': {'en': 'Tennis', 'es': 'Tenis'},
  'pool': {'en': 'Swimming Pool', 'es': 'Piscina'},
  'golf_course': {'en': 'Golf', 'es': 'Golf'},
  'stadium': {'en': 'Stadium', 'es': 'Estadio'},
  'celebration': {'en': 'Party', 'es': 'Fiesta'},
  'festival': {'en': 'Festival', 'es': 'Festival'},
  'camera': {'en': 'Photography', 'es': 'Fotografía'},
  'photo_library': {'en': 'Photos', 'es': 'Fotos'},
  // Health & Wellness
  'monitor_heart': {'en': 'Heart Health', 'es': 'Salud Cardíaca'},
  'local_hospital': {'en': 'Hospital', 'es': 'Hospital'},
  'fitness_center': {'en': 'Gym', 'es': 'Gimnasio'},
  'spa': {'en': 'Spa', 'es': 'Spa'},
  'psychology': {'en': 'Mental Health', 'es': 'Salud Mental'},
  'medication': {'en': 'Medication', 'es': 'Medicamento'},
  'health_and_safety': {'en': 'Health', 'es': 'Salud'},
  'self_improvement': {'en': 'Meditation', 'es': 'Meditación'},
  'medical_services': {'en': 'Medical Services', 'es': 'Servicios Médicos'},
  'biotech': {'en': 'Biotechnology', 'es': 'Biotecnología'},
  'vaccines': {'en': 'Vaccine', 'es': 'Vacuna'},
  'sports_gymnastics': {'en': 'Gymnastics', 'es': 'Gimnasia'},
  'emoji_emotions': {'en': 'Emotions', 'es': 'Emociones'},
  'nightlife': {'en': 'Nightlife', 'es': 'Vida Nocturna'},
  'bedroom_baby': {'en': 'Baby', 'es': 'Bebé'},
  // Home
  'home': {'en': 'Home', 'es': 'Hogar'},
  'chair': {'en': 'Furniture', 'es': 'Muebles'},
  'build': {'en': 'Repairs', 'es': 'Reparaciones'},
  'cleaning_services': {'en': 'Cleaning', 'es': 'Limpieza'},
  'lightbulb': {'en': 'Electricity', 'es': 'Electricidad'},
  'water_drop': {'en': 'Water', 'es': 'Agua'},
  'bed': {'en': 'Bedroom', 'es': 'Dormitorio'},
  'bathtub': {'en': 'Bathroom', 'es': 'Baño'},
  'countertops': {'en': 'Kitchen Counter', 'es': 'Encimera'},
  'yard': {'en': 'Garden', 'es': 'Jardín'},
  'lock': {'en': 'Security', 'es': 'Seguridad'},
  'wifi': {'en': 'Internet', 'es': 'Internet'},
  'tv_gen': {'en': 'Television', 'es': 'Televisor'},
  'security': {'en': 'Alarm', 'es': 'Alarma'},
  'plumbing': {'en': 'Plumbing', 'es': 'Fontanería'},
  'roofing': {'en': 'Roofing', 'es': 'Tejado'},
  // Shopping
  'shopping_bag': {'en': 'Shopping Bag', 'es': 'Bolsa de Compras'},
  'shopping_cart': {'en': 'Shopping Cart', 'es': 'Carrito de Compras'},
  'checkroom': {'en': 'Clothes', 'es': 'Ropa'},
  'watch': {'en': 'Watch', 'es': 'Reloj'},
  'phone_iphone': {'en': 'Smartphone', 'es': 'Teléfono'},
  'laptop': {'en': 'Laptop', 'es': 'Portátil'},
  'store': {'en': 'Store', 'es': 'Tienda'},
  'local_mall': {'en': 'Mall', 'es': 'Centro Comercial'},
  'redeem': {'en': 'Gift Card', 'es': 'Tarjeta Regalo'},
  'diamond': {'en': 'Jewelry', 'es': 'Joyería'},
  'dry_cleaning': {'en': 'Dry Cleaning', 'es': 'Tintorería'},
  'local_laundry_service': {'en': 'Laundry', 'es': 'Lavandería'},
  // Education & Work
  'school': {'en': 'School', 'es': 'Escuela'},
  'work': {'en': 'Work', 'es': 'Trabajo'},
  'business_center': {'en': 'Business', 'es': 'Negocio'},
  'edit': {'en': 'Writing', 'es': 'Escritura'},
  'science': {'en': 'Science', 'es': 'Ciencia'},
  'menu_book': {'en': 'Course', 'es': 'Curso'},
  'computer': {'en': 'Computer', 'es': 'Computadora'},
  'print': {'en': 'Printing', 'es': 'Impresión'},
  'library_books': {'en': 'Library', 'es': 'Biblioteca'},
  'calculate': {'en': 'Calculator', 'es': 'Calculadora'},
  'engineering': {'en': 'Engineering', 'es': 'Ingeniería'},
  'architecture': {'en': 'Architecture', 'es': 'Arquitectura'},
  // Travel & Places
  'travel_explore': {'en': 'Travel', 'es': 'Viajes'},
  'beach_access': {'en': 'Beach', 'es': 'Playa'},
  'landscape': {'en': 'Nature', 'es': 'Naturaleza'},
  'hotel': {'en': 'Hotel', 'es': 'Hotel'},
  'map': {'en': 'Map', 'es': 'Mapa'},
  'place': {'en': 'Location', 'es': 'Ubicación'},
  'luggage': {'en': 'Luggage', 'es': 'Equipaje'},
  'hiking': {'en': 'Hiking', 'es': 'Senderismo'},
  'camping': {'en': 'Cabin', 'es': 'Cabaña'},
  'sailing': {'en': 'Sailing', 'es': 'Vela'},
  'surfing': {'en': 'Surfing', 'es': 'Surf'},
  'park': {'en': 'Park', 'es': 'Parque'},
  // Miscellaneous
  'pets': {'en': 'Pets', 'es': 'Mascotas'},
  'card_giftcard': {'en': 'Gift', 'es': 'Regalo'},
  'volunteer_activism': {'en': 'Donations', 'es': 'Donaciones'},
  'child_care': {'en': 'Child Care', 'es': 'Cuidado Infantil'},
  'category': {'en': 'Category', 'es': 'Categoría'},
  'favorite': {'en': 'Favorites', 'es': 'Favoritos'},
  'star': {'en': 'Star', 'es': 'Estrella'},
  'emoji_nature': {'en': 'Nature', 'es': 'Naturaleza'},
  'notifications': {'en': 'Notifications', 'es': 'Notificaciones'},
  'cloud': {'en': 'Cloud', 'es': 'Nube'},
  'bolt': {'en': 'Energy', 'es': 'Energía'},
  'recycling': {'en': 'Recycling', 'es': 'Reciclaje'},
  'local_florist': {'en': 'Florist', 'es': 'Floristería'},
  'wb_sunny': {'en': 'Sunny', 'es': 'Soleado'},
};

/// Returns the human-readable label for an icon key in the given language.
///
/// Falls back to English, then the raw key if no translation is available.
String resolveCategoryIconLabel(String key, String languageCode) {
  final t = kCategoryIconTranslations[key];
  if (t == null) return key;
  return t[languageCode] ?? t['en'] ?? key;
}
